/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface FireComponents {}
  interface FireComponentsAttributes extends StencilHTMLAttributes {}

  interface FireSocialBar {}
  interface FireSocialBarAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'FireComponents': Components.FireComponents;
    'FireSocialBar': Components.FireSocialBar;
  }

  interface StencilIntrinsicElements {
    'fire-components': Components.FireComponentsAttributes;
    'fire-social-bar': Components.FireSocialBarAttributes;
  }


  interface HTMLFireComponentsElement extends Components.FireComponents, HTMLStencilElement {}
  var HTMLFireComponentsElement: {
    prototype: HTMLFireComponentsElement;
    new (): HTMLFireComponentsElement;
  };

  interface HTMLFireSocialBarElement extends Components.FireSocialBar, HTMLStencilElement {}
  var HTMLFireSocialBarElement: {
    prototype: HTMLFireSocialBarElement;
    new (): HTMLFireSocialBarElement;
  };

  interface HTMLElementTagNameMap {
    'fire-components': HTMLFireComponentsElement
    'fire-social-bar': HTMLFireSocialBarElement
  }

  interface ElementTagNameMap {
    'fire-components': HTMLFireComponentsElement;
    'fire-social-bar': HTMLFireSocialBarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
